### ISSUE TITLE
What are RPC endpoints for testnet and mainnet?

### ISSUE THREAD

**Issue by YakovL** [CosmWasm/CosmWasmJS#17]
basic example in docs goes:

```
const rpcEndpoint = "https://rpc.cliffnet.cosmwasm.com:443/";

async function main() {
  const client = await CosmWasmClient.connect(rpcEndpoint);
  console.log(client);
}
```

I've tried to log `const height = await client.getBlock()` and got 386,152.

According to https://gaia.bigdipper.live , block height of stargate-final (testnet) is 2,832,763 and https://cosmos.bigdipper.live shows 9,506,024 for cosmoshub-4 mainnet. What am I missing? What's this "386,152"?

What endpoint should I use for testnet? For mainnet? I've found that https://stargate.cosmos.network/testnet states that public RPC endpoint is 34.71.170.158:26657. I've tried both `const rpcEndpoint = "http://34.71.170.158:26657/";` and https version and got `Error: connect ECONNREFUSED 34.71.170.158:26657` for each.

**Comment by msteiner96** [comment]
Hi @YakovL !

In the docs branch we're currently starting to write docs for everything here. So I just checked your endpoint (http://34.71.170.158:26657/) and it doesn't seem to be online.

The `rpcEndpoint` used it the docs is for cliffnet-1. (https://github.com/CosmWasm/testnets/tree/master/cliffnet-1). 

If you want to work with another chain, you have to find either a public rpcEndpoint for it or host your own node.

**Comment by YakovL** [comment]
Thanks, this is very helpful indeed, I've implemented some bits and now need to understand the testnets ecosystem and pick one, I guess.

Please consider adding `const rpcEndpoint = "https://rpc.cosmos.network/";` bit into the readme.

**Comment by msteiner96** [comment]
We're using CosmWasm Testnets only for our docs. We can't list all cosmos sdk based chains in the readme, since their rpcEndpoints are changing and they're releasing too much to keep track of all.

But we should explain it better. Thanks for that advice!

/close
