### ISSUE TITLE
searchTx returns 502 for mainnet

### ISSUE THREAD

**Issue by YakovL** [CosmWasm/CosmWasmJS#21]
Here's what I've tried:

    const rpcEndpoint = "https://rpc.cosmos.network/";
    const client = CosmWasmClient.connect(rpcEndpoint);
    const someAddressFromMainnet = "cosmos1l0znsvddllw9knha3yx2svnlxny676d8ns7uys";
    const txs = await client.searchTx({
        sentFromOrTo: someAddressFromMainnet,
    });

Explorer shows that the account [exists](https://www.mintscan.io/cosmos/account/cosmos1l0znsvddllw9knha3yx2svnlxny676d8ns7uys) and has participated a number of txs, but I'm getting the 502 error.

Is it me doing something wrongly or CosmWasmJS/mainnet public RPC/explorer's problem?

**Comment by msteiner96** [comment]
I just tried it and got

```js
 response: {
    status: 502,
    statusText: 'Bad Gateway',
    headers: {
      date: 'Tue, 22 Feb 2022 08:05:50 GMT',
      'content-length': '11',
      'content-type': 'text/plain; charset=utf-8',
      connection: 'close'
    },
    config: {
      url: 'https://rpc.cosmos.network/',
      method: 'post',
      data: `{"jsonrpc":"2.0","id":158498933568,"method":"tx_search","params":{"query":"message.module='bank' AND transfer.recipient='cosmos1l0znsvddllw9knha3yx2svnlxny676d8ns7uys' AND tx.height>=0 AND tx.height<=9007199254740991","page":"1"}}`,
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.21.4',
        'Content-Length': 230
      },
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      }
    },
    ...
```

**Comment by msteiner96** [comment]
I just started to write docs for those methods. Check https://github.com/CosmWasm/CosmWasmJS/blob/docs/docs/clients/CosmWasmClient.md#transactions . Seems like you're using the wrong parameters.

**Comment by msteiner96** [comment]
Please check https://github.com/cosmos/cosmjs/issues/1049 . This is not a CosmWasmJS issue. Is that error also occuring when querying on a different chain or rpcEndpoint? Ideally use your own node.

**Comment by YakovL** [comment]
The thing is, no, querying different endpoints succeeds, at least `client.getBlock()` and `client.getBalance(account, "uatom")`, but you may be correct, thanks for pointing at the existing issue. This is not solved for me, but I think there's no point in keeping this open.
