### ISSUE TITLE
Remove unused bufferutil dependency

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/CosmWasmJS#37]
[bufferutil](https://www.npmjs.com/package/bufferutil) pulls in node-gyp-build, which is for building native code. Most likely we don't want any of those in here.

It was added in https://github.com/CosmWasm/CosmWasmJS/pull/27. Was that on purpose?

**Comment by msteiner96** [comment]
Hmm when building the umd bundle.js I get `Module not found: Error: Can't resolve 'bufferutil'` without it :/

**Comment by webmaster128** [comment]
Can you try to move it from dependenvies to devDependencies? Then apps uing this package don't pull in the dependency.
