### ISSUE TITLE
Upgrade CosmJS to ^0.28.3 and re-export normalizeBech32

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/CosmWasmJS#52]
After #48

**Comment by msteiner96** [comment]
@webmaster128  https://github.com/cosmos/cosmjs/blob/main/packages/encoding/src/index.ts It's not exported here, probably missing in https://github.com/cosmos/cosmjs/pull/1113 ?

**Comment by webmaster128** [comment]
Ouch, yes. Will do now.
