### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by karma1997** [CosmWasm/CosmWasmJS#69]
I created a new vue project, when I execute the content in the readme
![image](https://user-images.githubusercontent.com/31360943/168041884-672dad7b-8d37-4f4f-b09c-35bc887f34e1.png)

**Comment by daniel-farina** [comment]
> I created a new vue project, when I execute the content in the readme ![image](https://user-images.githubusercontent.com/31360943/168041884-672dad7b-8d37-4f4f-b09c-35bc887f34e1.png)

did you figure this out?

**Comment by karma1997** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by daniel-farina** [comment]
I found the answer on a vue3 project: 

// vite.config.ts
```export default defineConfig({
  define: {
    "global": {},
  },
});
```
